import React, { createContext, useContext, useState } from 'react';

type Language = 'ru' | 'en' | 'de' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.service': 'Сервис и гарантия',
    'nav.documents': 'Документы и сертификаты',
    'nav.contacts': 'Контакты',
    
    // Home page
    'home.hero.title': 'Техническое обслуживание и ремонт',
    'home.hero.subtitle': 'Оборудование складов ГСМ, ЦЗС и топливозаправочная техника',
    'home.hero.cta': 'Получить консультацию',
    'home.about.title': 'О МакТехникс',
    'home.about.p1': 'ООО «МакТехникс» основана в 2015 году. Компания оказывает качественные услуги по техническому обслуживанию и ремонту (ТОиР) оборудования складов ГСМ, ЦЗС и топливозаправочной техники.',
    'home.about.p2': 'Осуществляем ремонт автоцистерн, спецтехники коммунального назначения. Мы предлагаем услуги по обслуживанию и проведению ремонта на базе заказчика.',
    'home.about.p3': 'Опыт деловых отношений с самыми требовательными заказчиками научил нас внимательно относиться к пожеланиям клиентов на любом этапе сотрудничества.',
    'home.about.experience': 'На рынке более 10 лет',
    'home.advantages.title': 'Почему выбирают нас',
    'home.advantages.subtitle': 'Профессиональный подход к каждому проекту',
    'home.adv1.title': 'Гарантия качества',
    'home.adv1.desc': 'Соответствие стандартам с полным гарантийным покрытием',
    'home.adv2.title': 'Быстрое выполнение',
    'home.adv2.desc': 'Оптимизированные процессы для минимизации простоя техники',
    'home.adv3.title': 'Полный спектр услуг',
    'home.adv3.desc': 'От диагностики до капитального ремонта и модернизации',
    'home.adv4.title': 'Опыт работы',
    'home.adv4.desc': 'Более 10 лет на рынке технического обслуживания',
    'home.adv5.title': 'Квалифицированная команда',
    'home.adv5.desc': 'Опытные инженеры и сертифицированные специалисты',
    'home.adv6.title': 'Выездное обслуживание',
    'home.adv6.desc': 'Проведение ремонта и обслуживания на территории заказчика',
    'home.cta.title': 'Готовы начать проект?',
    'home.cta.text': 'Свяжитесь с нами сегодня для консультации и узнайте, как мы можем помочь с техническим обслуживанием вашего оборудования.',
    'home.cta.button': 'Связаться с нами',
    
    // Service page
    'service.title': 'Сервис и гарантия',
    'service.subtitle': 'Комплексная поддержка на протяжении всего жизненного цикла',
    'service1.title': 'ТОиР оборудования',
    'service1.desc': 'Техническое обслуживание и ремонт оборудования складов ГСМ, ЦЗС и топливозаправочной техники',
    'service2.title': 'Ремонт автоцистерн',
    'service2.desc': 'Профессиональный ремонт автоцистерн и спецтехники коммунального назначения',
    'service3.title': 'Конструирование и проектирование',
    'service3.desc': 'Разработка проектов модернизации оборудования складов ГСМ и топливозаправочной техники',
    'service4.title': 'Выездное обслуживание',
    'service4.desc': 'Проведение обслуживания и ремонта на базе заказчика',
    'service.warranty.title': 'Наши гарантийные обязательства',
    'service.warranty.p1': 'В МакТехникс мы гарантируем качество наших работ и услуг. Все виды технического обслуживания и ремонта поставляются с комплексной гарантией.',
    'service.warranty.p2': 'Наша гарантия включает:',
    'service.warranty.li1': 'Регулярные профилактические проверки',
    'service.warranty.li2': 'Приоритетная обработка сервисных запросов',
    'service.warranty.li3': 'Экспертная техническая поддержка',
    'service.warranty.li4': 'Полная документация по всем выполненным работам',
    'service.warranty.p3': 'Для получения подробной информации свяжитесь с нашим отделом обслуживания.',
    
    // Footer
    'footer.company': 'О компании',
    'footer.inn': 'ИНН',
    'footer.address': 'Адрес регистрации',
    'footer.addressDetails': 'Московская область, город Домодедово, ул Ильюшина (Авиационный Мкр.), д. 1а, офис 5',
    'footer.quickLinks': 'Быстрые ссылки',
    'footer.info': 'Информация',
    'footer.description': 'Профессиональное обслуживание специализированного оборудования',
    
    // Documents page
    'docs.title': 'Документы и сертификаты',
    'docs.subtitle': 'Наша компания имеет все необходимые сертификаты и лицензии',
    'docs.download': 'Скачать PDF',
    'docs.quality.title': 'Сертифицированное качество',
    'docs.quality.text': 'Все наши услуги соответствуют требованиям международных стандартов качества',
    'docs.doc1.title': 'Сертификат соответствия №1 2020',
    'docs.doc1.desc': 'Сертификат соответствия требованиям',
    'docs.doc2.title': 'Сертификат соответствия №2 2020',
    'docs.doc2.desc': 'Сертификат соответствия требованиям',
    'docs.doc3.title': 'Сертификат соответствия №3 2020',
    'docs.doc3.desc': 'Сертификат соответствия требованиям',
    'docs.doc4.title': 'Сертификат соответствия №4 2020',
    'docs.doc4.desc': 'Сертификат соответствия требованиям',
    'docs.doc5.title': 'Сертификат 2018',
    'docs.doc5.desc': 'Сертификат соответствия 2018 года',
    'docs.doc6.title': 'Лицензия',
    'docs.doc6.desc': 'Лицензия на осуществление деятельности',
    'docs.doc7.title': 'Решение 2018',
    'docs.doc7.desc': 'Решение о регистрации',
    'docs.doc8.title': 'Перечень услуг 2018',
    'docs.doc8.desc': 'Полный перечень предоставляемых услуг',
    'docs.cat.certificates': 'Сертификаты',
    'docs.cat.licenses': 'Лицензии',
    'docs.cat.documents': 'Документы',
    'docs.cat.services': 'Услуги',
    
    // Contacts page
    'contacts.title': 'Контакты',
    'contacts.subtitle': 'Мы всегда рады ответить на ваши вопросы',
    'contacts.form.title': 'Отправить сообщение',
    'contacts.form.name': 'Имя',
    'contacts.form.email': 'Email',
    'contacts.form.message': 'Сообщение',
    'contacts.form.submit': 'Отправить',
    'contacts.form.success': 'Сообщение отправлено!',
    'contacts.form.error': 'Ошибка отправки',
    'contacts.info.title': 'Контактная информация',
    'contacts.address': 'Адрес',
    'contacts.address.value': 'Московская обл., г. Домодедово, мкр. Авиационный, ул. Ильюшина, д.1 а.',
    'contacts.phone': 'Телефон',
    'contacts.email': 'Email',
    'contacts.hours': 'Время работы',
    'contacts.hours.value': 'пн-пт: 09:00-18:00, сб-вс: выходные',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.service': 'Service & Warranty',
    'nav.documents': 'Documents & Certificates',
    'nav.contacts': 'Contacts',
    
    // Home page
    'home.hero.title': 'Maintenance and Repair',
    'home.hero.subtitle': 'Fuel storage equipment, CZS and refueling equipment',
    'home.hero.cta': 'Get Consultation',
    'home.about.title': 'About MakTechniks',
    'home.about.p1': 'MakTechniks LLC was founded in 2015. The company provides quality services for maintenance and repair of fuel storage equipment, CZS and refueling equipment.',
    'home.about.p2': 'We repair tank trucks and municipal special equipment. We offer on-site maintenance and repair services at the customer\'s facility.',
    'home.about.p3': 'Experience of business relations with the most demanding customers taught us to pay attention to clients\' wishes at any stage of cooperation.',
    'home.about.experience': 'Over 10 years in the market',
    'home.advantages.title': 'Why Choose Us',
    'home.advantages.subtitle': 'Professional approach to every project',
    'home.adv1.title': 'Quality Guarantee',
    'home.adv1.desc': 'Compliance with standards with full warranty coverage',
    'home.adv2.title': 'Fast Execution',
    'home.adv2.desc': 'Optimized processes to minimize equipment downtime',
    'home.adv3.title': 'Full Range of Services',
    'home.adv3.desc': 'From diagnostics to major repairs and modernization',
    'home.adv4.title': 'Work Experience',
    'home.adv4.desc': 'Over 10 years in the maintenance market',
    'home.adv5.title': 'Qualified Team',
    'home.adv5.desc': 'Experienced engineers and certified specialists',
    'home.adv6.title': 'On-Site Service',
    'home.adv6.desc': 'Repair and maintenance at customer\'s location',
    'home.cta.title': 'Ready to Start a Project?',
    'home.cta.text': 'Contact us today for consultation and learn how we can help with your equipment maintenance.',
    'home.cta.button': 'Contact Us',
    
    // Service page
    'service.title': 'Service & Warranty',
    'service.subtitle': 'Comprehensive support throughout the entire lifecycle',
    'service1.title': 'Equipment Maintenance',
    'service1.desc': 'Technical maintenance and repair of fuel storage, CZS and refueling equipment',
    'service2.title': 'Tank Truck Repair',
    'service2.desc': 'Professional repair of tank trucks and municipal special equipment',
    'service3.title': 'Design and Engineering',
    'service3.desc': 'Development of modernization projects for fuel storage and refueling equipment',
    'service4.title': 'On-Site Service',
    'service4.desc': 'Maintenance and repair at customer\'s facility',
    'service.warranty.title': 'Our Warranty Commitments',
    'service.warranty.p1': 'At MakTechniks we guarantee the quality of our work and services. All maintenance and repair services come with comprehensive warranty.',
    'service.warranty.p2': 'Our warranty includes:',
    'service.warranty.li1': 'Regular preventive inspections',
    'service.warranty.li2': 'Priority service request processing',
    'service.warranty.li3': 'Expert technical support',
    'service.warranty.li4': 'Complete documentation for all work performed',
    'service.warranty.p3': 'For detailed information, contact our service department.',
    
    // Footer
    'footer.company': 'About Company',
    'footer.inn': 'TIN',
    'footer.address': 'Registration Address',
    'footer.addressDetails': 'Moscow Region, Domodedovo, Ilyushin St. (Aviation District), 1a, office 5',
    'footer.quickLinks': 'Quick Links',
    'footer.info': 'Information',
    'footer.description': 'Professional specialized equipment service',
    
    // Documents page
    'docs.title': 'Documents & Certificates',
    'docs.subtitle': 'Our company has all necessary certificates and licenses',
    'docs.download': 'Download PDF',
    'docs.quality.title': 'Certified Quality',
    'docs.quality.text': 'All our services comply with international quality standards',
    'docs.doc1.title': 'Compliance Certificate №1 2020',
    'docs.doc1.desc': 'Certificate of compliance with requirements',
    'docs.doc2.title': 'Compliance Certificate №2 2020',
    'docs.doc2.desc': 'Certificate of compliance with requirements',
    'docs.doc3.title': 'Compliance Certificate №3 2020',
    'docs.doc3.desc': 'Certificate of compliance with requirements',
    'docs.doc4.title': 'Compliance Certificate №4 2020',
    'docs.doc4.desc': 'Certificate of compliance with requirements',
    'docs.doc5.title': 'Certificate 2018',
    'docs.doc5.desc': 'Compliance certificate 2018',
    'docs.doc6.title': 'License',
    'docs.doc6.desc': 'License to carry out activities',
    'docs.doc7.title': 'Resolution 2018',
    'docs.doc7.desc': 'Registration resolution',
    'docs.doc8.title': 'Services List 2018',
    'docs.doc8.desc': 'Complete list of provided services',
    'docs.cat.certificates': 'Certificates',
    'docs.cat.licenses': 'Licenses',
    'docs.cat.documents': 'Documents',
    'docs.cat.services': 'Services',
    
    // Contacts page
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'We are always happy to answer your questions',
    'contacts.form.title': 'Send Message',
    'contacts.form.name': 'Name',
    'contacts.form.email': 'Email',
    'contacts.form.message': 'Message',
    'contacts.form.submit': 'Send',
    'contacts.form.success': 'Message sent!',
    'contacts.form.error': 'Sending error',
    'contacts.info.title': 'Contact Information',
    'contacts.address': 'Address',
    'contacts.address.value': 'Moscow region, Domodedovo, Aviatsionny district, Ilyushin str., 1a',
    'contacts.phone': 'Phone',
    'contacts.email': 'Email',
    'contacts.hours': 'Working Hours',
    'contacts.hours.value': 'Mon-Fri: 09:00-18:00, Sat-Sun: closed',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.service': 'Service & Garantie',
    'nav.documents': 'Dokumente & Zertifikate',
    'nav.contacts': 'Kontakte',
    
    // Home page
    'home.hero.title': 'Wartung und Reparatur',
    'home.hero.subtitle': 'Kraftstoffanlagen, CZS und Betankungsausrüstung',
    'home.hero.cta': 'Beratung erhalten',
    'home.about.title': 'Über MakTechniks',
    'home.about.p1': 'MakTechniks LLC wurde 2015 gegründet. Das Unternehmen bietet qualitativ hochwertige Dienstleistungen für Wartung und Reparatur von Kraftstoffanlagen, CZS und Betankungsausrüstung.',
    'home.about.p2': 'Wir reparieren Tankwagen und kommunale Spezialausrüstung. Wir bieten Wartungs- und Reparaturdienstleistungen vor Ort beim Kunden an.',
    'home.about.p3': 'Die Erfahrung in Geschäftsbeziehungen mit anspruchsvollsten Kunden hat uns gelehrt, auf Kundenwünsche in jeder Phase der Zusammenarbeit zu achten.',
    'home.about.experience': 'Über 10 Jahre am Markt',
    'home.advantages.title': 'Warum uns wählen',
    'home.advantages.subtitle': 'Professioneller Ansatz für jedes Projekt',
    'home.adv1.title': 'Qualitätsgarantie',
    'home.adv1.desc': 'Einhaltung von Standards mit vollständiger Garantieabdeckung',
    'home.adv2.title': 'Schnelle Ausführung',
    'home.adv2.desc': 'Optimierte Prozesse zur Minimierung von Geräteausfallzeiten',
    'home.adv3.title': 'Vollständige Dienstleistungspalette',
    'home.adv3.desc': 'Von Diagnose bis Generalüberholung und Modernisierung',
    'home.adv4.title': 'Arbeitserfahrung',
    'home.adv4.desc': 'Über 10 Jahre auf dem Wartungsmarkt',
    'home.adv5.title': 'Qualifiziertes Team',
    'home.adv5.desc': 'Erfahrene Ingenieure und zertifizierte Spezialisten',
    'home.adv6.title': 'Vor-Ort-Service',
    'home.adv6.desc': 'Reparatur und Wartung am Standort des Kunden',
    'home.cta.title': 'Bereit, ein Projekt zu starten?',
    'home.cta.text': 'Kontaktieren Sie uns heute für eine Beratung und erfahren Sie, wie wir bei der Wartung Ihrer Ausrüstung helfen können.',
    'home.cta.button': 'Kontaktieren Sie uns',
    
    // Service page
    'service.title': 'Service & Garantie',
    'service.subtitle': 'Umfassende Unterstützung während des gesamten Lebenszyklus',
    'service1.title': 'Gerätewartung',
    'service1.desc': 'Technische Wartung und Reparatur von Kraftstoffanlagen, CZS und Betankungsausrüstung',
    'service2.title': 'Tankwagen-Reparatur',
    'service2.desc': 'Professionelle Reparatur von Tankwagen und kommunaler Spezialausrüstung',
    'service3.title': 'Design und Engineering',
    'service3.desc': 'Entwicklung von Modernisierungsprojekten für Kraftstoffanlagen und Betankungsausrüstung',
    'service4.title': 'Vor-Ort-Service',
    'service4.desc': 'Wartung und Reparatur am Standort des Kunden',
    'service.warranty.title': 'Unsere Garantieverpflichtungen',
    'service.warranty.p1': 'Bei MakTechniks garantieren wir die Qualität unserer Arbeit und Dienstleistungen. Alle Wartungs- und Reparaturdienstleistungen werden mit umfassender Garantie geliefert.',
    'service.warranty.p2': 'Unsere Garantie umfasst:',
    'service.warranty.li1': 'Regelmäßige vorbeugende Inspektionen',
    'service.warranty.li2': 'Prioritäre Bearbeitung von Serviceanfragen',
    'service.warranty.li3': 'Fachkundiger technischer Support',
    'service.warranty.li4': 'Vollständige Dokumentation aller durchgeführten Arbeiten',
    'service.warranty.p3': 'Für detaillierte Informationen kontaktieren Sie unsere Serviceabteilung.',
    
    // Footer
    'footer.company': 'Über das Unternehmen',
    'footer.inn': 'Steuer-ID',
    'footer.address': 'Registrierungsadresse',
    'footer.addressDetails': 'Region Moskau, Domodedovo, Iljuschin-Straße (Luftfahrtviertel), 1a, Büro 5',
    'footer.quickLinks': 'Schnelllinks',
    'footer.info': 'Information',
    'footer.description': 'Professioneller Service für Spezialausrüstung',
    
    // Documents page
    'docs.title': 'Dokumente & Zertifikate',
    'docs.subtitle': 'Unser Unternehmen verfügt über alle erforderlichen Zertifikate und Lizenzen',
    'docs.download': 'PDF herunterladen',
    'docs.quality.title': 'Zertifizierte Qualität',
    'docs.quality.text': 'Alle unsere Dienstleistungen entsprechen internationalen Qualitätsstandards',
    'docs.doc1.title': 'Konformitätszertifikat №1 2020',
    'docs.doc1.desc': 'Konformitätszertifikat mit Anforderungen',
    'docs.doc2.title': 'Konformitätszertifikat №2 2020',
    'docs.doc2.desc': 'Konformitätszertifikat mit Anforderungen',
    'docs.doc3.title': 'Konformitätszertifikat №3 2020',
    'docs.doc3.desc': 'Konformitätszertifikat mit Anforderungen',
    'docs.doc4.title': 'Konformitätszertifikat №4 2020',
    'docs.doc4.desc': 'Konformitätszertifikat mit Anforderungen',
    'docs.doc5.title': 'Zertifikat 2018',
    'docs.doc5.desc': 'Konformitätszertifikat 2018',
    'docs.doc6.title': 'Lizenz',
    'docs.doc6.desc': 'Lizenz zur Durchführung von Tätigkeiten',
    'docs.doc7.title': 'Beschluss 2018',
    'docs.doc7.desc': 'Registrierungsbeschluss',
    'docs.doc8.title': 'Dienstleistungsverzeichnis 2018',
    'docs.doc8.desc': 'Vollständige Liste der erbrachten Dienstleistungen',
    'docs.cat.certificates': 'Zertifikate',
    'docs.cat.licenses': 'Lizenzen',
    'docs.cat.documents': 'Dokumente',
    'docs.cat.services': 'Dienstleistungen',
    
    // Contacts page
    'contacts.title': 'Kontakte',
    'contacts.subtitle': 'Wir beantworten gerne Ihre Fragen',
    'contacts.form.title': 'Nachricht senden',
    'contacts.form.name': 'Name',
    'contacts.form.email': 'E-Mail',
    'contacts.form.message': 'Nachricht',
    'contacts.form.submit': 'Senden',
    'contacts.form.success': 'Nachricht gesendet!',
    'contacts.form.error': 'Sendefehler',
    'contacts.info.title': 'Kontaktinformationen',
    'contacts.address': 'Adresse',
    'contacts.address.value': 'Region Moskau, Domodedovo, Bezirk Aviatsionny, Iljuschin-Str., 1a',
    'contacts.phone': 'Telefon',
    'contacts.email': 'E-Mail',
    'contacts.hours': 'Arbeitszeiten',
    'contacts.hours.value': 'Mo-Fr: 09:00-18:00, Sa-So: geschlossen',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.service': '服务与保修',
    'nav.documents': '文件与证书',
    'nav.contacts': '联系方式',
    
    // Home page
    'home.hero.title': '维护与维修',
    'home.hero.subtitle': '燃料储存设备、CZS和加油设备',
    'home.hero.cta': '获取咨询',
    'home.about.title': '关于MakTechniks',
    'home.about.p1': 'MakTechniks有限责任公司成立于2015年。公司为燃料储存设备、CZS和加油设备的维护和维修提供优质服务。',
    'home.about.p2': '我们维修油罐车和市政专用设备。我们提供客户现场的维护和维修服务。',
    'home.about.p3': '与要求最严格的客户建立业务关系的经验教会了我们在合作的任何阶段都要关注客户的愿望。',
    'home.about.experience': '市场经验超过10年',
    'home.advantages.title': '为什么选择我们',
    'home.advantages.subtitle': '对每个项目的专业方法',
    'home.adv1.title': '质量保证',
    'home.adv1.desc': '符合标准并提供全面保修',
    'home.adv2.title': '快速执行',
    'home.adv2.desc': '优化流程以减少设备停机时间',
    'home.adv3.title': '全方位服务',
    'home.adv3.desc': '从诊断到大修和现代化',
    'home.adv4.title': '工作经验',
    'home.adv4.desc': '在维护市场超过10年',
    'home.adv5.title': '专业团队',
    'home.adv5.desc': '经验丰富的工程师和认证专家',
    'home.adv6.title': '现场服务',
    'home.adv6.desc': '在客户现场进行维修和维护',
    'home.cta.title': '准备开始项目？',
    'home.cta.text': '立即联系我们进行咨询，了解我们如何帮助您进行设备维护。',
    'home.cta.button': '联系我们',
    
    // Service page
    'service.title': '服务与保修',
    'service.subtitle': '整个生命周期的全面支持',
    'service1.title': '设备维护',
    'service1.desc': '燃料储存、CZS和加油设备的技术维护和维修',
    'service2.title': '油罐车维修',
    'service2.desc': '油罐车和市政专用设备的专业维修',
    'service3.title': '设计与工程',
    'service3.desc': '燃料储存和加油设备现代化项目的开发',
    'service4.title': '现场服务',
    'service4.desc': '在客户现场进行维护和维修',
    'service.warranty.title': '我们的保修承诺',
    'service.warranty.p1': '在MakTechniks，我们保证工作和服务的质量。所有维护和维修服务都提供全面保修。',
    'service.warranty.p2': '我们的保修包括：',
    'service.warranty.li1': '定期预防性检查',
    'service.warranty.li2': '优先处理服务请求',
    'service.warranty.li3': '专业技术支持',
    'service.warranty.li4': '所有完成工作的完整文档',
    'service.warranty.p3': '有关详细信息，请联系我们的服务部门。',
    
    // Footer
    'footer.company': '关于公司',
    'footer.inn': '纳税人识别号',
    'footer.address': '注册地址',
    'footer.addressDetails': '莫斯科州，多莫杰多沃市，伊留申街（航空区），1a，办公室5',
    'footer.quickLinks': '快速链接',
    'footer.info': '信息',
    'footer.description': '专业特种设备服务',
    
    // Documents page
    'docs.title': '文件与证书',
    'docs.subtitle': '我们公司拥有所有必要的证书和许可证',
    'docs.download': '下载PDF',
    'docs.quality.title': '认证质量',
    'docs.quality.text': '我们的所有服务都符合国际质量标准',
    'docs.doc1.title': '合规证书 №1 2020',
    'docs.doc1.desc': '符合要求的证书',
    'docs.doc2.title': '合规证书 №2 2020',
    'docs.doc2.desc': '符合要求的证书',
    'docs.doc3.title': '合规证书 №3 2020',
    'docs.doc3.desc': '符合要求的证书',
    'docs.doc4.title': '合规证书 №4 2020',
    'docs.doc4.desc': '符合要求的证书',
    'docs.doc5.title': '证书 2018',
    'docs.doc5.desc': '2018年合规证书',
    'docs.doc6.title': '许可证',
    'docs.doc6.desc': '开展活动的许可证',
    'docs.doc7.title': '决议 2018',
    'docs.doc7.desc': '注册决议',
    'docs.doc8.title': '服务清单 2018',
    'docs.doc8.desc': '提供服务的完整清单',
    'docs.cat.certificates': '证书',
    'docs.cat.licenses': '许可证',
    'docs.cat.documents': '文件',
    'docs.cat.services': '服务',
    
    // Contacts page
    'contacts.title': '联系方式',
    'contacts.subtitle': '我们随时乐意回答您的问题',
    'contacts.form.title': '发送消息',
    'contacts.form.name': '姓名',
    'contacts.form.email': '电子邮件',
    'contacts.form.message': '消息',
    'contacts.form.submit': '发送',
    'contacts.form.success': '消息已发送！',
    'contacts.form.error': '发送错误',
    'contacts.info.title': '联系信息',
    'contacts.address': '地址',
    'contacts.address.value': '莫斯科地区，多莫杰多沃市，航空区，伊留申街1a号',
    'contacts.phone': '电话',
    'contacts.email': '电子邮件',
    'contacts.hours': '工作时间',
    'contacts.hours.value': '周一至周五：09:00-18:00，周六至周日：休息',
  },
};
